### ISSUE TITLE
San Diego Code Enforcement

### ISSUE THREAD

**Issue by MrMaksimize** [citygram/citygram-services#33]
**Definition:** A way to be notified of code enforcement activity near an address in San Diego.
**Data Source:**: [OpenDSD](http://www.sandiego.gov/development-services/opendsd/)
**ETL:**: Data is already being ETLed out to OpenDSD, and we just grab the latest.
**Template:**: "There's been a code enforcement case updated near you at: *[Street Address]*.<br/> The violation is "*[Description]*".<br/> You can find out more at: *[url with more info]*

URL is https://sd-notifications.herokuapp.com/dsd/code-enforcement

Thank you!

**Comment by bcipolli** [comment]
@invisiblefunnel @eeeschwartz What are the next steps to have this endpoint serviced by citygram-services? Glad to submit a PR if needed, but not sure where to go from here.

**Comment by invisiblefunnel** [comment]
Looping in @bigfleet.

**Comment by bcipolli** [comment]
@bigfleet any chance we can get some instructions on what to do next? Endpoint is still live, ready to go.

**Comment by bigfleet** [comment]
@bcipolli Cool!  Looks like you're ready to evaluate [going live](https://github.com/codeforamerica/citygram/wiki/Going-Live).  I can bring on the dataset in advance of bringing San Diego up on the web interface.  But that page describes everything needed to get up and going.

**Comment by bigfleet** [comment]
@bcipolli Oh, one last thing-- your CaseID field does meet the uniqueness criteria, but for our purposes, [we need that field to be named ID](https://github.com/codeforamerica/citygram/wiki/Citygram-Dataset-Best-Practices#minimum-requirements).

**Comment by bcipolli** [comment]
Thanks @bigfleet ! @MrMaksimize I will take a look at these.

**Comment by bigfleet** [comment]
@bcipolli If that's closed, it looks like you're through the first of [these steps](https://github.com/codeforamerica/citygram/wiki/Bring-Citygram-to-your-city.).  I await the second and to bring you online!

**Comment by bigfleet** [comment]
San Diego launched awhile back
