### ISSUE TITLE
Charlotte Historic District

### ISSUE THREAD

**Issue by bigfleet** [citygram/citygram-services#34]
Currently suffering from a NoMethodFound error:

```
2015-08-18T16:26:20.082408+00:00 app[web.1]: NoMethodError - undefined method `[]' for nil:NilClass:
2015-08-18T16:26:20.082413+00:00 app[web.1]: 	/app/lib/spy_glass/registry/clt-historic-district-reviews.rb:13:in `block (2 levels) in
```

In addition, the title needs to be revisited.

**Comment by masonpackard** [comment]
In terms of the title, it looks to match the verbage found on the CityGram site.
![image](https://cloud.githubusercontent.com/assets/5422830/9469102/2ea7565c-4b13-11e5-88cf-2a7aafbe84b7.png)
![image](https://cloud.githubusercontent.com/assets/5422830/9469076/120a80a0-4b13-11e5-9e00-b63ebd60b77d.png)

The source / data feed verbage from the City of Charlotte, shows "CharlotteHistoricDistrictCases".  So, here might be a couple of options:
* Leave as it is to best match from the CityGram API provider to CityGram website consumer
* Change to best match the City of Charlotte's verbage and wording

Any thoughts?

**Comment by masonpackard** [comment]
Take a look at this pull request, https://github.com/citygram/citygram-services/pull/35, as the title that is referenced for each charlotte historic district review object, is set to combine the "AppNum" with the "ProjAddr"  This would allow a unique combination of data to provide a way for the user to search through their email, sorting by subject.

**Comment by bigfleet** [comment]
Here's my version of the city's feedback, edited for brevity: “New request for Tree Removal – Landscape Plan at 804 E Worthington Av.  For more, call (704) 336-2205 or visit http://j.mp/clt-chd-reviews”

**Comment by masonpackard** [comment]
So, all of this 

> “New request for Tree Removal – Landscape Plan at 804 E Worthington Av. For more, call (704) 336-2205 or visit http://j.mp/clt-chd-reviews”

would go into the title area of the json feed? 

Also, does citygram or the city have an official link shortener?

**Comment by bigfleet** [comment]
An interpolated version would go in the title.  "Tree Removal - Landscape Plan" is one of the fields, so is the address.  The rest is stock text.

We can bring up the idea of having an official URL shortener later.  For now, we will use our own.

**Comment by bigfleet** [comment]
This delivered about 2000 messages today.  Closed!
